### ISSUE TITLE
BACKEND : connection closed 

### ISSUE THREAD

**Issue by tomekl007** [tomekl007/initlearn#157]
could not inspect JDBC autocommit mode
SqlExceptionHelper   : This connection has been closed.

threw exception [Request processing failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: could not inspect JDBC autocommit mode; nested exception is org.hibernate.exception.JDBCConnectionException: could not inspect JDBC autocommit mode] with root cause
2016-02-24T17:18:40.751868+00:00 app[web.1]: 2016-02-24 17:18:40.751 ERROR 3 --- [io-25301-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : This connection has been closed.
2016-02-24T17:18:40.752072+00:00 app[web.1]: 2016-02-24 17:18:40.752  WARN 3 --- [io-25301-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 08003
2016-02-24T17:18:40.755074+00:00 app[web.1]: 	at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:820) ~[postgresql-9.4-1201-jdbc4.jar!/:9.4]
2016-02-24T17:18:40.755071+00:00 app[web.1]: 
2016-02-24T17:18:40.755075+00:00 app[web.1]: 	at org.postgresql.jdbc2.AbstractJdbc2Connection.getAutoCommit(AbstractJdbc2Connection.java:781) ~[postgresql-9.4-1201-jdbc4.jar!/:9.4]
2016-02-24T17:18:40.755075+00:00 app[web.1]: 	at sun.reflect.GeneratedMethodAccessor49.invoke(Unknown Source) ~[na:na]
2016-02-24T17:18:40.755076+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_72-cedar14]
2016-02-24T17:18:40.755077+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_72-cedar14]
2016-02-24T17:18:40.755090+00:00 app[web.1]: 	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:91) ~[spring-data-jpa-1.9.1.RELEASE.jar!/:na]
2016-02-24T17:18:40.755073+00:00 app[web.1]: org.postgresql.util.PSQLException: This connection has been closed.
2016-02-24T17:18:40.755079+00:00 app[web.1]: 	at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81) ~[tomcat-jdbc-8.0.28.jar!/:na]
2016-02-24T17:18:40.755078+00:00 app[web.1]: 	at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[tomcat-jdbc-8.0.28.jar!/:na]
2016-02-24T17:18:40.755110+00:00 app[web.1]: 	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-4.2.3.RELEASE.jar!/:4.2.3.RELEASE]
2016-02-24T17:18:40.755084+00:00 app[web.1]: 	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:103) ~[hibernate-core-4.3.11.Final.jar!/:4.3.11.Final]
2016-02-24T17:18:40.755088+00:00 app[web.1]: 	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:114) ~[spring-data-jpa-1.9.1.RELEASE.jar!/:na]

**Comment by tomekl007** [comment]
http://stackoverflow.com/questions/31881250/heroku-postgres-this-connection-has-been-closed
